### ISSUE TITLE
Node 18 broken my deploy

### ISSUE THREAD

**Issue by rmeira** [fumeapp/action#1]
Guys, i have error bellow on use this action

```
Node.js v18.14.1
    error Command failed with exit code 1.
    yarn run v1.22.19
    $ nuxt build
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about 
    this command.
Error: Process completed with exit code 2.
```

Anyone now how to solved this?

**Comment by acidjazz** [comment]
@rmeira add this to your action:

```yaml
      - uses: actions/setup-node@v3
        with:
          node-version: 16
```

**Comment by rmeira** [comment]
@acidjazz thanks, this work for me!

**Comment by acidjazz** [comment]
FYI @rmeira I launched fume-cli v2.x which now supports NodeJS v18 - this action installs the latest version at all times so if you just remove that setup-node it should work!!

On another note any new fume project will also be given the v18 Lambda Runtime, so by removing/adding your environments you can make sure you are v18 all the way!


Also if you don't mind letting me know as well here that'd be awesome :)
